### ISSUE TITLE
They couldn't be dismissed.

### ISSUE THREAD

**Issue by 94HanA** [iforgotmysocks/CaravanAdventures#2]
![image](https://github.com/iforgotmysocks/CaravanAdventures/assets/111541485/9dbb265e-3732-4477-8968-0459a4dd6478)

It's Korean but you might understand.

Everytime they came, I tried to dismiss them (several times) but never worked.

the dismissing is new option its added at 1.5.

"dismissed" button appears normally, but they don't.

**Comment by iforgotmysocks** [comment]
Dismissing them should work fine, tested that when updating to 1.5. Do you get any error in the log when you try to dismiss? Most likely a mod compatibility issue.

Edit: Ah, the pawn that initiates the story doesn't have to be the same pawn that is the main trader pawn. You probably may just have to look for a second pawn that you can talk to to trade with. That one will have the dismiss option. :)

**Comment by 94HanA** [comment]
I don't know if it's a related error or not, but here is.
this error appears every ticks, and log avoid it when it's reached 998 times.

you are right, I'm using a lot of mods(over 200) so might it's not from CaravanAdventures, or just compatibility issue.
however I just meant to let you know the dismiss bug, it didn't interfere with the actual gameplay- so if it's working normally, it doesn't matter. Sorry to take your time. have fun!

Exception while ticking lord with job RimWorld.LordJob_TradeWithColony: 
System.NullReferenceException: Object reference not set to an instance of an object
[Ref 54FFD28A] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
Verse.AI.Group.LordManager:LordManagerTick ()
Verse.Map:MapPostTick ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch3 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch0 (Verse.Root_Play)

**Comment by iforgotmysocks** [comment]
All good. I'm always happy about feedback and reports, thanks for posting. Another person recently reported an issue with the initial caravan, but we couldn't track down what mod is causing trouble. Do you think you could post a hugslib log with your error? It might get us closer to finding the culprit.

**Comment by 94HanA** [comment]
![image](https://github.com/iforgotmysocks/CaravanAdventures/assets/111541485/3d176ba7-a074-4c02-877e-f56b23c0a8d0)

I tried, but "Failed to collect data" error blocks me. I'm so sorry I couldn't help you.
I think this error is also caused by other mod.

**Comment by iforgotmysocks** [comment]
Alright, thanks for trying tho. :)
